import {FC, ReactElement} from 'react'
import styles from "../styles/MainLayout.module.scss"
import Head from "next/head"

interface IMainLayout {
  children: ReactElement
}

const MainLayout: FC<IMainLayout> = ({children}) => {
  return (
    <>
      <Head>
        <title>Serverless auth app by Argen</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          {children}
        </div>
      </main>
    </>
  )
}

export default MainLayout
